# Generated by Django 5.1.4 on 2024-12-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.student'),
        ),
    ]
